# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgis
  encoding: utf-8
  database: aa_development
  pool: 5

staging:
  adapter: postgis
  encoding: utf-8
  database: aa_staging
  pool: 5

test:
  adapter: postgis
  encoding: utf-8
  database: aa_test
  pool: 5
