development:
  adapter: postgis
  encoding: utf-8
  database: aa_development
  pool: 5
  host: localhost
  username: postgres

staging:
  adapter: postgis
  encoding: utf-8
  database: aa_staging
  pool: 5

test:
  adapter: postgis
  encoding: utf-8
  database: aa_test
  pool: 5
  host: localhost
  username: postgres
